WIP build: check os version & missing packages

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,40 @@
 #!/usr/bin/env bash
-#TODO: check distro and packages
+
+# Check for installed packages
+if [ -f /etc/os-release ]; then
+    . /etc/os-release
+    DISTRO=$NAME
+    if [ "$DISTRO"=="Arch Linux" ]; then
+        if ! pacman -Qq cmake gdb git sdl2 patchelf  &>/dev/null; then
+            echo "Missing package(s). Please make sure you have installed all required packages."
+            read -p "Do you still want to build? (Y/n)" -n 1 -r
+            echo
+            if [[ $REPLY =~ ^[Nn]$ ]]; then
+                exit 1
+            fi
+        fi
+    elif [ "$DISTRO"=="Ubuntu" ]; then
+    # Should be `dpkg-query -s`? Does this fail with a missing package?`
+        if ! dpkg -s cmake g++ gdb git libsdl2-dev zlib1g-dev patchelf  &>/dev/null; then
+            echo "Missing package(s). Please make sure you have installed all required packages."
+            read -p "Do you still want to build? (Y/n)" -n 1 -r
+            echo
+            if [[ $REPLY =~ ^[Nn]$ ]]; then
+                exit 1
+            fi
+        fi
+    elif [ "$DISTRO"=="Fedora" ]; then
+    # Does a missing package produce an error with `dnf check`?
+        if ! dnf check cmake gcc-c++ gdb git libstdc++-static mesa-libGL-devel SDL2-devel zlib-devel libX11-devel patchelf  &>/dev/null; then
+            echo "Missing package(s). Please make sure you have installed all required packages."
+            read -p "Do you still want to build? (Y/n)" -n 1 -r
+            echo
+            if [[ $REPLY =~ ^[Nn]$ ]]; then
+                exit 1
+            fi
+        fi
+    fi
+fi
 
 function echo_orange {
 	echo -e "\\e[33m$*\\e[0m"
